name: Run Scripts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'  # 毎日08:00 JST（UTCで23:00）

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        env:
          TEST_MODE: '1'  # ← 実行テスト時のみ1にする（投稿や履歴更新を抑止）
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          GCP_SERVICE_ACCOUNT_B64: ${{ secrets.GCP_SERVICE_ACCOUNT_B64 }}
        run: python main.py
