# .github/workflows/weekly-post.yml
name: mansion-thread-poster-weekly

on:
  schedule:
    # 14:00 UTC = 23:00 JST 毎週金曜
    - cron: '0 14 * * FRI'
  workflow_dispatch:  # ← 手動実行ボタンも付けておくと便利

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GCP_SERVICE_ACCOUNT_B64: ${{ secrets.GCP_SERVICE_ACCOUNT_B64 }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
