name: post-runner

on:
  schedule:
    # = JST 08:00（UTC 前日 23:00）
    - cron: '0 23 * * *'
    # = JST 15:00（UTC 06:00）
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリ取得
      - uses: actions/checkout@v4

      # 2) Python セットアップ
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3) 依存インストール  ← ここを修正
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests requests_oauthlib gspread google-auth pytz

      # 4) 投稿スクリプト実行
      - name: Run poster
        run: python post_to_x.py
        env:
          SPREADSHEET_ID:          ${{ secrets.SPREADSHEET_ID }}
          GCP_SERVICE_ACCOUNT_B64: ${{ secrets.GCP_SERVICE_ACCOUNT_B64 }}
          TWITTER_API_KEY:         ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET:      ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN:    ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET:   ${{ secrets.TWITTER_ACCESS_SECRET }}
